### ISSUE TITLE
本地与服务器界面显示不一致

### ISSUE THREAD

**Issue by Hanwall** [Hanwall/HANWALL.GITHUB.IO#1]

**Comment by Hanwall** [comment]
URL 填写错误导致的主题在GITHUB PAGES 显示不正常，HTTP和HTTPS的区别

**Comment by SDH-IT-HO** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
t0thkr1s, @syedhali, @shaojunyang, @mybestcool, @cnydo, @dgrr, @ChaoticCrypto, @louiszgm, @rnyn, @eagle453, @ch3rub1m, @prestonhunter, @imjdl, @askiebaby, @bing2008, @killeder, @ttbowen, @kodycode, @black2996, @smileymi6, @theLeroy, @tomagoyaky, @robotparty, @kllmctrl, @hurskar, @xiaotiansky, @sunsetyan, @SushritPasupuleti, @adrianmejias, @ylxg12345, @reza35, @rikster, @beetlepig, @amazingandyyy, @damujen, @siemens84cn, @coollineme, @jack-siren, @zhenalexfan, @jiangkai886, @jeskol, @danielblair, @JackTWallace, @KhanShaheb34, @rblaine95, @enayet123, @mohrezani, @nikzaugg, @GordenChoy, @kaykybbboot, @shenzhigang, @franmaranchello, @mujinqi, @mabehiry, @Nahuelito, @HuaxuDuan, @bluenet13, @rjcnitsche, @liulxiang, @Coinward, @chenlexing, @congim, @yidahis, @siddarth7, @viren-proxy, @vinberm, @yinengy, @jaeminChung, @nicoboou, @abdllah2, @boboyuwu, @pmattos, @valinsky, @DeeLMind, @riwala, @cksmct, @AugustFirst, @GuiminChu, @x1957, @fengjw1, @rock-git, @lyledavids, @samwalls, @maczhao, @outdamud, @R-Y-M-R, @navvvidi, @klenty-rajesh, @AldousCheng, @coding364, @muhammad-hamdi, @JoinBelieve, @WahedSlet, @kouzhudong, @bogdanlungu, @vihaankapoor, @wanmaoxian, @mariokandut, @joaozaratehyangl, @nogut0123, @domsteil, @LjtGitHub, @yoshocon, @kevinho, @usattc, @automagicaly, @lanhaolong20161111, @Navissy, @yangpeng-chn, @RockyYan1994, @NagyGeorgeScripps, @louisnelza, @SongShuo, @tianhongce, @yosoyubik, @jaibeer72, @pnshsh, @asiachrispy, @christopher19, @Heribertosgp, @demesvardestin, @Monkpie, @WuCh1k1n, @MichalZalecki, @julian59189, @dsalin, @Brdjx, @guima-seifer, @ritchiejacobs, @greavettey, @kbqncf, @yomajo, @cn0xroot, @HsingPeng, @Keitrina, @jasonz1987, @JSBACH100, @harrytran998, @rmahtab0079, @jakehemmerle, @ncoelho, @ozanh, @tuxthepenguin84, @HunterHeston, @KyleTang, @caterpillar, @271264921, @hu2013953589hejinbo96, @EdgarLGB, @Breezess, @GAUTHAM31, @Dinines, @Wendelcorp, @McGiggity, @JamesWuChina, @noodleswww, @cilick, @Caldis, @nurseforge, @Ekove, @MrinalJain17, @StellarRing, @AkhilNaidu09, @watanabemakoto, @joncody, @yetkinsari, @telecomsr, @kerlw, @GZWgssmart, @sun5526, @qar, @rahulmutt, @mr-ma, @1156721874, @Ryochan7, @whitewalker-sa, @ipudu, @santdeleon, @Ahkari, @EricSeltzer, @zhanglj007, @lichang333, @speedyouth, @sunphy, @redeltaglio, @kwiky, @bitdonnie, @frankxia2013, @Smy0521, @apierp1, @macrocan, @iyakexi, @paitonic, @jammeroo7, @Hsankesara, @curtis74, @wangbeidongEyrum, @aopi1125, @vbe0201, @tgys, @gujiuxiang, @JimWongM, @zhcn, @trysomething792, @brianium, @chappjc, @xiaorong919, @jnMetaCode, @Dre56213, @shainakrumme, @liyinhgqw, @timothy-b, @bonuskarte, @huanvliu, @792289314, @fan-n-akiyama, @ruancomelli, @fad1, @hubaokun, @dry11orange, @ezhuo, @Jerick26, @chemi123, @lianghuiyuan, @yular, @pradeepgangwar, @BhargavMahajan, @zouyoufang, @Yhanqiu, @bnuzhoub, @fengkai090602, @bekorn, @hector12free, @BdonC, @hanyouqing, @funkwave, @mghlm, @forestfoxx, @TsungLi-Wang, @hungtseyee, @gaoshoutuo, @1-st, @Jmgmartig, @WXB506, @icervot, @neuromancerbiz

**Comment by dgrr** [comment]
bro wth, I don't speak chinese, don't mention me

**Comment by dgrr** [comment]
I don't give a fuck about your shitty bald ass airdrop
